<a href="https://colab.research.google.com/github/Binary-Digits/TensorFlows/blob/main/constant_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

# Constant Tensors


Constant tensor operations

In [3]:
# creating a constant tensor with values 1, 2, 3, 4 and shape 2 x 2
const_a = tf.constant([1, 2, 3, 4], dtype=tf.float32, shape=(2, 2))
const_a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [4]:
# view some common atrributes
print('the value of const_a is: ', const_a.numpy())
print('the shape of const_a is: ', const_a.shape)
print('the dtype of const_a is: ', const_a.dtype)
print('the device to run const_a is: ', const_a.device)

the value of const_a is:  [[1. 2.]
 [3. 4.]]
the shape of const_a is:  (2, 2)
the dtype of const_a is:  <dtype: 'float32'>
the device to run const_a is:  /job:localhost/replica:0/task:0/device:CPU:0


In [5]:
# create a 2 x 3 matrix with all values as 0
matZero = tf.zeros(shape=(2, 3), dtype=tf.float32)
matZero

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [6]:
# convert a constant matrix values to 0
newMatZero = tf.zeros_like(const_a)
newMatZero

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [7]:
# create a 2 x 3 matriz with all values being 8
mat8 = tf.fill([2, 3], 8)
mat8

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[8, 8, 8],
       [8, 8, 8]], dtype=int32)>

In [8]:
# create a random tensor
matRandom = tf.random.normal([5, 5], mean=0, stddev=1, seed=10)
matRandom.numpy()

array([[ 1.6368568 ,  1.0018815 ,  1.2575399 ,  0.45011964,  1.1136591 ],
       [-1.1902049 , -0.37428668, -0.883854  , -0.03430768, -0.5932982 ],
       [-0.298225  , -1.9923381 ,  0.4145472 ,  1.316359  , -0.57848054],
       [ 1.8102627 , -0.5162807 ,  0.4151929 , -1.4721702 ,  1.0285027 ],
       [ 0.67973435, -0.09504995, -1.0033755 ,  2.6278005 , -0.6885831 ]],
      dtype=float32)

In [9]:
# create a list and convert it to tensor
list_f = [1, 2, 3, 4, 5, 6]
print(type(list_f))

<class 'list'>


In [10]:
tensor_f = tf.convert_to_tensor(list_f, dtype=tf.float32)
tensor_f

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6.], dtype=float32)>

# variable tensors


In [11]:
# create a variable tensor
var_tf = tf.Variable(tf.ones(shape=(2, 3), dtype=tf.float32))
var_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [12]:
# read the variable value
var_tf.read_value()

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [13]:
# assign a variable value
new_var = [[1, 2, 3], [4, 5, 6]]
var_tf.assign(new_var)
# read the value
var_tf.read_value

<bound method BaseResourceVariable.read_value of <tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>>

variable addition and sutraction

In [14]:
# add a variable
var_tf.assign_add(tf.ones([2, 3]))
var_tf.read_value

<bound method BaseResourceVariable.read_value of <tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[2., 3., 4.],
       [5., 6., 7.]], dtype=float32)>>

In [15]:
# subtract a variable
var_tf.assign_sub(tf.ones([2, 3]))
var_tf


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

# Tensor Slicing and Indexing

In [16]:
# create a 4-D tensor containing 4 images, each with size 100 x 100 x 3
tensor_h = tf.random.normal([4, 100, 100, 3])
tensor_h

<tf.Tensor: shape=(4, 100, 100, 3), dtype=float32, numpy=
array([[[[ 5.75007796e-01,  3.12542260e-01, -1.08370113e+00],
         [ 1.03248429e+00,  1.65268853e-01,  1.06057515e-02],
         [ 9.60180685e-02,  8.44770432e-01,  1.67516935e+00],
         ...,
         [-6.53626978e-01,  1.82314205e+00, -9.85001683e-01],
         [-5.14738858e-01, -1.55100867e-01,  4.87259954e-01],
         [-1.12661302e+00,  4.59955871e-01, -1.24403846e+00]],

        [[-1.62389040e+00,  1.26497503e-02, -6.17516160e-01],
         [ 1.14323425e+00,  1.92101824e+00, -1.14262092e+00],
         [ 9.63095546e-01, -4.62287813e-01,  1.31728542e+00],
         ...,
         [-1.95454133e+00,  4.70267057e-01, -3.44297051e+00],
         [-4.08010393e-01,  2.36026931e+00,  6.36012703e-02],
         [-8.45993832e-02, -5.88901281e-01,  3.20191085e-01]],

        [[-8.22476149e-01, -2.40465283e+00, -6.51122987e-01],
         [-1.21939087e+00, -5.10350764e-01,  1.00395238e+00],
         [ 1.50935441e-01, -1.33423150e+00

In [17]:
# extract the first image
tensor_h[0, :, :, : ]

<tf.Tensor: shape=(100, 100, 3), dtype=float32, numpy=
array([[[ 5.75007796e-01,  3.12542260e-01, -1.08370113e+00],
        [ 1.03248429e+00,  1.65268853e-01,  1.06057515e-02],
        [ 9.60180685e-02,  8.44770432e-01,  1.67516935e+00],
        ...,
        [-6.53626978e-01,  1.82314205e+00, -9.85001683e-01],
        [-5.14738858e-01, -1.55100867e-01,  4.87259954e-01],
        [-1.12661302e+00,  4.59955871e-01, -1.24403846e+00]],

       [[-1.62389040e+00,  1.26497503e-02, -6.17516160e-01],
        [ 1.14323425e+00,  1.92101824e+00, -1.14262092e+00],
        [ 9.63095546e-01, -4.62287813e-01,  1.31728542e+00],
        ...,
        [-1.95454133e+00,  4.70267057e-01, -3.44297051e+00],
        [-4.08010393e-01,  2.36026931e+00,  6.36012703e-02],
        [-8.45993832e-02, -5.88901281e-01,  3.20191085e-01]],

       [[-8.22476149e-01, -2.40465283e+00, -6.51122987e-01],
        [-1.21939087e+00, -5.10350764e-01,  1.00395238e+00],
        [ 1.50935441e-01, -1.33423150e+00, -1.13783395e+00],


In [18]:
# extract one slice at an interval of two images
tensor_h[: : 2, ...]

<tf.Tensor: shape=(2, 100, 100, 3), dtype=float32, numpy=
array([[[[ 5.75007796e-01,  3.12542260e-01, -1.08370113e+00],
         [ 1.03248429e+00,  1.65268853e-01,  1.06057515e-02],
         [ 9.60180685e-02,  8.44770432e-01,  1.67516935e+00],
         ...,
         [-6.53626978e-01,  1.82314205e+00, -9.85001683e-01],
         [-5.14738858e-01, -1.55100867e-01,  4.87259954e-01],
         [-1.12661302e+00,  4.59955871e-01, -1.24403846e+00]],

        [[-1.62389040e+00,  1.26497503e-02, -6.17516160e-01],
         [ 1.14323425e+00,  1.92101824e+00, -1.14262092e+00],
         [ 9.63095546e-01, -4.62287813e-01,  1.31728542e+00],
         ...,
         [-1.95454133e+00,  4.70267057e-01, -3.44297051e+00],
         [-4.08010393e-01,  2.36026931e+00,  6.36012703e-02],
         [-8.45993832e-02, -5.88901281e-01,  3.20191085e-01]],

        [[-8.22476149e-01, -2.40465283e+00, -6.51122987e-01],
         [-1.21939087e+00, -5.10350764e-01,  1.00395238e+00],
         [ 1.50935441e-01, -1.33423150e+00

In [19]:
# slice data from the last element
tensor_h[::-1]

<tf.Tensor: shape=(4, 100, 100, 3), dtype=float32, numpy=
array([[[[-3.73600394e-01, -1.27671719e+00, -1.06520236e+00],
         [ 2.04158115e+00,  4.92803484e-01, -5.45215905e-01],
         [ 1.74589396e+00,  3.37224305e-01, -4.05389905e-01],
         ...,
         [ 3.44560534e-01, -8.33277583e-01, -2.74765670e-01],
         [-5.70457101e-01,  1.56513846e+00,  8.67178559e-01],
         [-1.76727459e-01,  2.40468353e-01,  4.38066542e-01]],

        [[-4.87575710e-01, -5.60471237e-01, -8.05874109e-01],
         [-1.57953274e+00, -5.47931269e-02, -8.07205498e-01],
         [-1.34719753e+00, -7.20566928e-01, -1.06026185e+00],
         ...,
         [-2.30523631e-01,  1.92688560e+00,  5.16930401e-01],
         [ 9.63015854e-03,  6.39412403e-02,  4.85458672e-01],
         [-1.71496451e+00, -2.24030852e-01, -5.92654824e-01]],

        [[ 1.43622971e+00, -1.54768729e+00,  1.53487599e+00],
         [ 1.12945974e+00,  3.57999712e-01, -1.00966644e+00],
         [-1.23273396e+00, -1.12070715e+00

# Tensor Arithmetic Operations

Arithmetic Operator

In [20]:
a = tf.ones([2, 2], dtype=tf.int32)
b = tf.fill([2, 2], 2)
print(a, "\n", b)

tf.Tensor(
[[1 1]
 [1 1]], shape=(2, 2), dtype=int32) 
 tf.Tensor(
[[2 2]
 [2 2]], shape=(2, 2), dtype=int32)


In [21]:
# addition
tf.add(a, b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 3],
       [3, 3]], dtype=int32)>

In [22]:
# subtraction
tf.subtract(a, b)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-1, -1],
       [-1, -1]], dtype=int32)>

In [23]:
# multiplication
tf.multiply(a, b)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 2],
       [2, 2]], dtype=int32)>

In [24]:
# division
tf.divide(a, b)


<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.5, 0.5],
       [0.5, 0.5]])>

Matrix multiplication

In [25]:
tf.matmul(a, b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 4],
       [4, 4]], dtype=int32)>

Tensor Statistics Collection

In [26]:
argmax_sample_1 = tf.constant([[1, 3, 2], [2, 5, 8], [7, 5, 9]])
print("Input tensor: ",argmax_sample_1)

Input tensor:  tf.Tensor(
[[1 3 2]
 [2 5 8]
 [7 5 9]], shape=(3, 3), dtype=int32)


In [27]:
# locate the maximum value by column
max_sample_1 = tf.argmax(argmax_sample_1, axis=0)
max_sample_1.numpy()

array([2, 1, 2])

In [28]:
# locate the maximum value by row
max_sample_2 = tf.argmax(argmax_sample_1, axis=1)
max_sample_2.numpy()

array([1, 2, 2])

# Dimension-based arithmetic operations

In [29]:
# create a constant tensor
reduce_sample_1 = tf.constant([1, 2, 3, 4, 5, 6], shape=(2, 3))
reduce_sample_1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [30]:
# calculate the sum of all elements in a tensor
tf.reduce_sum(reduce_sample_1, axis=None).numpy()

21

In [31]:
# calculate the sum of elements in each column
tf.reduce_sum(reduce_sample_1, axis=0).numpy()

array([5, 7, 9], dtype=int32)

In [32]:
# claculate the sum of elements in each row
tf.reduce_sum(reduce_sample_1, axis=1).numpy()

array([ 6, 15], dtype=int32)

# Tensor Concatenation and Splitting

In [34]:
# generate two random 4D tensors
concat_sample_1 = tf.random.normal([4, 100, 100, 3])
concat_sample_1.shape

TensorShape([4, 100, 100, 3])

In [35]:
concat_sample_2 = tf.random.normal([40, 100, 100, 3])
concat_sample_2.shape

TensorShape([40, 100, 100, 3])

In [37]:
# concatenate both samples
concated_samples = tf.concat([concat_sample_1, concat_sample_2], axis=0)
concated_samples.shape

TensorShape([44, 100, 100, 3])

# Tensor Sorting

In [53]:
# creating a random tensor
sort_sample = tf.random.shuffle(tf.range(10))
print("random sample: ", sort_sample)


random sample:  tf.Tensor([8 3 2 0 4 1 6 7 5 9], shape=(10,), dtype=int32)


In [54]:
# sorting sample by value
sorted_sample_1 = tf.sort(sort_sample, direction='ASCENDING')
print('tensors sorted in ascending order', sorted_sample_1)

tensors sorted in ascending order tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [55]:
# sorting samples by index
sorted_sample_2 = tf.argsort(sort_sample, direction='ASCENDING')
print("indexes of elements in ascending order", sorted_sample_2.numpy())

indexes of elements in ascending order [3 5 2 1 4 8 6 7 0 9]


In [58]:
# sort out the 5 largest elements
values, index = tf.nn.top_k(sort_sample, k=5)
print("input tensor: ", sort_sample)
print("first five values in ascending order: ", values.numpy())
print('indexes of the first five values in ascending order', index.numpy())


input tensor:  tf.Tensor([8 3 2 0 4 1 6 7 5 9], shape=(10,), dtype=int32)
first five values in ascending order:  [9 8 7 6 5]
indexes of the first five values in ascending order [9 0 7 6 8]
